services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "D:/Learning/DEZoomcamp/git/data-engineering-zoomcamp/week-1/docker-SQL/ny-taxi-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5342"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"